// Словарь i18n (RU/EN). tr() и currentLang живут в index.html.
export const STRINGS = {
  ru: {
    signIn:'Войти в аккаунт', continueWithGoogle:'Войти через Google',
    continueWithApple:'Войти через Apple', or:'или',
    passwordPlaceholder:'Пароль (мин. 6 символов)',
    signin:'Войти', signup:'Регистрация',
    myCharts:'Мои карты', appTitle:'Натальная карта',
    back:'Назад', editData:'Редактировать данные',
    saveChartHeader:'Сохранить карту', settings:'Настройки',
    language:'Язык', smGeneral:'Общие', smChart:'Карта', smTimeline:'Таймлайн',
    smSearch:'Поиск настроек…', smNothing:'Ничего не найдено', smConfigure:'Настроить…',
    elements:'Стихии', login:'Войти', charts:'📂 Карты', logout:'Выйти',
    transitsTab:'Прогностика', natal:'Натал', forecast:'Прогноз',
    transits:'Транзиты', progressions:'Прогрессии', directions:'Дирекции',
    v2ModeNatal:'Натал', v2ModeTransit:'Транзит', v2ModeProgressed:'Прогр.', v2ModeDirection:'Дирекц.',
    timeline:'Таймлайн', info:'Инфо', grid:'Сетка',
    nameLabel:'Имя', namePlaceholder:'Имя человека',
    birthDateLabel:'Дата рождения', birthTimeLabel:'Время (местное)',
    birthPlaceLabel:'Место рождения', cityPlaceholder:'Начните вводить город…',
    latLabel:'Широта', lonLabel:'Долгота', utcOffsetLabel:'UTC смещение, ч',
    buildChart:'Построить карту', cancel:'Отменить',
    saveChartBtn:'💾 Сохранить карту', recentCharts:'Последние карты',
    prevYear:'-1 год', yearLbl:'год', prevMonth:'-1 месяц', monthLbl:'мес',
    prevDay:'-1 день', dayLbl:'день', today:'Сегодня', todayBtn:'↺ Сегодня',
    clickToSelectDate:'Нажмите для выбора даты',
    nextDay:'+1 день', nextMonth:'+1 месяц', nextYear:'+1 год',
    houseLabel:'Дом:', fromLabel:'с', durationLabel:'на', yearsUnit:'лет',
    calculate:'Рассчитать',
    loading:'Загрузка Swiss Ephemeris…', ready:'Готово.',
    sweError:'Ошибка Swiss Ephemeris: ',
    detectingTimezone:'Определяю часовой пояс…',
    timezoneNotDetected:'часовой пояс не определён, введите вручную',
    searching:'Поиск…', placeNotFound:'Место не найдено. Введите координаты вручную.',
    geocodingError:'Ошибка геокодинга.', fillAllFields:'Заполните все поля.',
    error:'Ошибка: ', saved:'✓ Сохранено', saveError:'Ошибка',
    saving:'Сохранить', computingTransits:'Вычисление транзитов…', tlAngles:'Углы',
    rpAddWidget:'Добавить виджет', rpPanelMenu:'Меню панели',
    paletteNewTab:'Новая вкладка', paletteCmdNatal:'Новая карта', paletteCmdSynastry:'Синастрия',
    paletteCmdHorary:'Хорар', paletteCmdElection:'Элекция', paletteSoon:'скоро',
    paletteSearchPh:'Открыть карту…', paletteLoginHint:'Войдите, чтобы видеть сохранённые карты',
    paletteNoResults:'Ничего не найдено',
    panelTabDignities:'Достоинства', digDayChart:'Дневная карта', digNightChart:'Ночная карта',
    digColDom:'Об', digColExalt:'Экз', digColTrip:'Трип', digColTerm:'Терм', digColFace:'Фас',
    digPeregrine:'перегрин',
    horaryQuestionLabel:'Вопрос', horaryQuestionPh:'Текст вопроса…',
    horaryDateLabel:'Дата вопроса', horaryPlaceLabel:'Место (астролог)',
    electionWhatLabel:'Что подбираем', electionWhatPh:'Напр.: подписание договора…',
    electionMomentLabel:'Момент', electionPlaceLabel:'Место', electionFolder:'Электив',
    snapshotsTitle:'Снимки', snapEmpty:'Крутите момент и нажмите + чтобы сохранить', delete:'Удалить',
    momentTitle:'Момент', navModeDate:'Дата', navModeTime:'Время',
    horaryFolder:'Хорары', outcomeYes:'Сбылся', outcomeNo:'Нет', outcomePartial:'Частично',
    lpHomeTitle:'Главная', lpTabLibrary:'Библиотека',
    lpLibSearchPh:'Имя, город или: сатурн трин луна',
    lpSearchFound:'найдено: {n}',
    lpSearchScopeHint:'Темпоральный поиск (tr:/prog:/dir:) появится внутри кейса — здесь ищутся натальные факты.',
    lpHouseShort:'дом', lpScopeOnly:'фильтр',
    lpDslPartial:'Похоже на аспект-поиск — продолжите: аспект / знак / дом N / rx. Справка — «?»',
    lpHelpTitle:'Справка по поиску',
    lpCheat:'<b>Аспекты:</b> <code>сатурн асп плутон</code> · <code>венера 120 юпитер</code> · <code>saturn trine moon orb&lt;2</code><br><b>Положение:</b> <code>солнце в лев</code> · <code>луна дом 4</code> · <code>меркурий rx</code> · <code>марс соед asc</code><br><b>Скоуп:</b> <code>type:хорар</code> · <code>-type:элекция</code> · <code>folder:Клиенты</code> · <code>-folder:Тест</code> · чип папки — тоже скоуп<br><b>Логика:</b> AND / И / запятая · OR / ИЛИ',
    synastryFolder:'Синастрии', synTitle:'Синастрия', synBuild:'Построить синастрию',
    synSubjectA:'Первый человек', synSubjectB:'Второй человек',
    synPickSaved:'Выбрать из сохранённых…', synFillBoth:'Заполните данные обоих людей.',
    synViewA:'Карта А', synViewB:'Карта Б', synViewBoth:'Синастрия',
    digRowDom:'Обитель', digRowExalt:'Экзальтация', digRowTrip:'Триплицитет', digRowTerm:'Терм',
    digRowFace:'Фас', digRowDetr:'Изгнание', digRowFall:'Падение', digRowScore:'Балл',
    panelTabAspFlow:'События', afPastEvents:'Прошлые события', afFutureEvents:'Будущие события',
    noTransits:'Нет активных транзитов в этом периоде.',
    computingDots:'вычисление…', noFastTransits:'нет быстрых транзитов',
    noChartData:'Нет данных карты', computingForecast:'Вычисление…',
    enterEmailPass:'Введите email и пароль.', signingIn:'Вход…',
    minPassword:'Пароль — минимум 6 символов.', registering:'Регистрация…',
    checkEmail:'Проверьте почту — отправлена ссылка подтверждения.',
    chartsLoading:'Загрузка…',
    noSavedCharts:'Сохранённых карт нет.<br>Постройте карту и нажмите «Сохранить».',
    deleteTitle:'Удалить', deleteConfirm:'Удалить «{name}»?',
    renameTitle:'Переименовать', addToFolderTitle:'Добавить в папку',
    renamePrompt:'Новое имя карты:',
    chartFallback:'Карта',
    planetVisibility:'Планеты натала', resetAll:'Сбросить все',
    progLunarPhases:'Фазы прогр. Луны',
    privacyMode:'Скрыть имя и дату',
    skyNowTitle:'Небо сейчас', skySetPlace:'указать место',
    vocFromTo:'☽︎ без курса {from}–{to}', vocUntil:'☽︎ без курса до {to}',
    homeEvents:'События', homeAll:'Все', homePinned:'Закреплённые',
    homeSearchPlaceholder:'Поиск по имени или городу…', newChart:'+ Новая карта',
    homeNothingFound:'Ничего не найдено',
    pinTitle:'Закрепить', unpinTitle:'Открепить', groupTitle:'Группа',
    exactOn:'точный', turnsYears:'исполняется {n}',
    panelTabData:'Данные', panelTabNotes:'Заметки', panelTabGrades:'Градусы', panelTabAspects:'Аспекты',
    noteNew:'+ Новая заметка', noteUntitled:'Без названия',
    notesEmpty:'Заметок пока нет',
    notesLoginFirst:'Войдите, чтобы делать заметки',
    notesSaveChartFirst:'Сохраните карту, чтобы делать заметки',
    notesError:'Ошибка загрузки заметок',
    noteTitlePlaceholder:'Название…',
    noteDeleteConfirm:'Удалить заметку «{name}»?',
    noteBackTitle:'К списку', notePreviewTitle:'Просмотр', noteExportTitle:'Экспорт .md',
    phaseName_0:'Новолуние', phaseName_45:'Серп',
    phaseName_90:'Первая четверть', phaseName_135:'Горб',
    phaseName_180:'Полнолуние', phaseName_225:'Рассеивающая',
    phaseName_270:'Последняя четверть', phaseName_315:'Бальзамическая',
    byMonths:'по месяцам', byYears:'по годам', prLabel:'Пр', dirLabel:'Дир',
    prPrefix:'пр ', dirPrefix:'дир ', trPrefix:'тр', natPrefix:'нат',
    houseWord:'Дом', cuspWord:'Куспид',
    angularNames:{ 0:'Асцендент', 3:'IC', 6:'Десцендент', 9:'MC' },
    rulerLabel:'Упр:', housePrefix:'Дом ',
    pl_sun:'Солнце', pl_moon:'Луна', pl_mercury:'Меркурий', pl_venus:'Венера',
    pl_mars:'Марс', pl_jupiter:'Юпитер', pl_saturn:'Сатурн', pl_uranus:'Уран',
    pl_neptune:'Нептун', pl_pluto:'Плутон', pl_nnode:'С. Узел',
    pl_lilith:'Лилит', pl_chiron:'Хирон', pl_snode:'Ю. Узел', pl_nodes:'Узлы',
    signs:['Овен','Телец','Близнецы','Рак','Лев','Дева','Весы','Скорпион','Стрелец','Козерог','Водолей','Рыбы'],
    asp_conjunction:'Соединение', asp_sextile:'Секстиль',
    asp_square:'Квадрат', asp_trine:'Трин', asp_opposition:'Оппозиция',
    months:['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек'],
  },
  en: {
    signIn:'Sign In', continueWithGoogle:'Continue with Google',
    continueWithApple:'Continue with Apple', or:'or',
    passwordPlaceholder:'Password (min. 6 chars)',
    signin:'Sign In', signup:'Register',
    myCharts:'My Charts', appTitle:'Natal Chart',
    back:'Back', editData:'Edit data',
    saveChartHeader:'Save chart', settings:'Settings',
    language:'Language', smGeneral:'General', smChart:'Chart', smTimeline:'Timeline',
    smSearch:'Search settings…', smNothing:'Nothing found', smConfigure:'Configure…',
    elements:'Elements', login:'Sign In', charts:'📂 Charts', logout:'Sign Out',
    transitsTab:'Transits', natal:'Natal', forecast:'Forecast',
    transits:'Transits', progressions:'Progressions', directions:'Directions',
    v2ModeNatal:'Natal', v2ModeTransit:'Transit', v2ModeProgressed:'Progr.', v2ModeDirection:'Direct.',
    timeline:'Timeline', info:'Info', grid:'Grid',
    nameLabel:'Name', namePlaceholder:"Person's name",
    birthDateLabel:'Birth date', birthTimeLabel:'Birth time (local)',
    birthPlaceLabel:'Birth place', cityPlaceholder:'Start typing city…',
    latLabel:'Latitude', lonLabel:'Longitude', utcOffsetLabel:'UTC offset, h',
    buildChart:'Build chart', cancel:'Cancel',
    saveChartBtn:'💾 Save chart', recentCharts:'Recent charts',
    prevYear:'-1 year', yearLbl:'year', prevMonth:'-1 month', monthLbl:'mon',
    prevDay:'-1 day', dayLbl:'day', today:'Today', todayBtn:'↺ Today',
    clickToSelectDate:'Click to select date',
    nextDay:'+1 day', nextMonth:'+1 month', nextYear:'+1 year',
    houseLabel:'House:', fromLabel:'from', durationLabel:'for', yearsUnit:'yrs',
    calculate:'Calculate',
    loading:'Loading Swiss Ephemeris…', ready:'Ready.',
    sweError:'Swiss Ephemeris error: ',
    detectingTimezone:'Detecting timezone…',
    timezoneNotDetected:'timezone not detected, enter manually',
    searching:'Searching…', placeNotFound:'Place not found. Enter coordinates manually.',
    geocodingError:'Geocoding error.', fillAllFields:'Please fill in all fields.',
    error:'Error: ', saved:'✓ Saved', saveError:'Error',
    saving:'Save', computingTransits:'Computing transits…', tlAngles:'Angles',
    rpAddWidget:'Add widget', rpPanelMenu:'Panel menu',
    paletteNewTab:'New tab', paletteCmdNatal:'New chart', paletteCmdSynastry:'Synastry',
    paletteCmdHorary:'Horary', paletteCmdElection:'Election', paletteSoon:'soon',
    paletteSearchPh:'Open a chart…', paletteLoginHint:'Sign in to see saved charts',
    paletteNoResults:'Nothing found',
    panelTabDignities:'Dignities', digDayChart:'Day chart', digNightChart:'Night chart',
    digColDom:'Dom', digColExalt:'Exal', digColTrip:'Trip', digColTerm:'Term', digColFace:'Face',
    digPeregrine:'peregrine',
    horaryQuestionLabel:'Question', horaryQuestionPh:'Question text…',
    horaryDateLabel:'Date of question', horaryPlaceLabel:'Place (astrologer)',
    electionWhatLabel:'What to elect', electionWhatPh:'e.g. signing a contract…',
    electionMomentLabel:'Moment', electionPlaceLabel:'Place', electionFolder:'Election',
    snapshotsTitle:'Snapshots', snapEmpty:'Crank the moment and press + to save', delete:'Delete',
    momentTitle:'Moment', navModeDate:'Date', navModeTime:'Time',
    horaryFolder:'Хорары', outcomeYes:'Fulfilled', outcomeNo:'No', outcomePartial:'Partially',
    lpHomeTitle:'Home', lpTabLibrary:'Library',
    lpLibSearchPh:'Name, city or: saturn trine moon',
    lpSearchFound:'found: {n}',
    lpSearchScopeHint:'Temporal search (tr:/prog:/dir:) will be available inside a case — this searches natal facts.',
    lpHouseShort:'house', lpScopeOnly:'filter',
    lpDslPartial:'Looks like an aspect search — continue: aspect / sign / house N / rx. Help — “?”',
    lpHelpTitle:'Search help',
    lpCheat:'<b>Aspects:</b> <code>saturn asp pluto</code> · <code>venus 120 jupiter</code> · <code>saturn trine moon orb&lt;2</code><br><b>Position:</b> <code>sun in leo</code> · <code>moon house 4</code> · <code>mercury rx</code> · <code>mars conj asc</code><br><b>Scope:</b> <code>type:horary</code> · <code>-type:election</code> · <code>folder:Clients</code> · <code>-folder:Test</code> · folder chip works as scope too<br><b>Logic:</b> AND / comma · OR',
    synastryFolder:'Синастрии', synTitle:'Synastry', synBuild:'Build synastry',
    synSubjectA:'Person A', synSubjectB:'Person B',
    synPickSaved:'Pick from saved…', synFillBoth:'Fill in both people’s data.',
    synViewA:'Chart A', synViewB:'Chart B', synViewBoth:'Synastry',
    digRowDom:'Domicile', digRowExalt:'Exaltation', digRowTrip:'Triplicity', digRowTerm:'Term',
    digRowFace:'Face', digRowDetr:'Detriment', digRowFall:'Fall', digRowScore:'Score',
    panelTabAspFlow:'Events', afPastEvents:'Past events', afFutureEvents:'Future events',
    noTransits:'No active transits in this period.',
    computingDots:'computing…', noFastTransits:'no fast transits',
    noChartData:'No chart data', computingForecast:'Computing…',
    enterEmailPass:'Enter email and password.', signingIn:'Signing in…',
    minPassword:'Password must be at least 6 characters.', registering:'Registering…',
    checkEmail:'Check your email — a confirmation link has been sent.',
    chartsLoading:'Loading…',
    noSavedCharts:'No saved charts.<br>Build a chart and click Save.',
    deleteTitle:'Delete', deleteConfirm:'Delete "{name}"?',
    renameTitle:'Rename', addToFolderTitle:'Add to folder',
    renamePrompt:'New chart name:',
    chartFallback:'Chart',
    planetVisibility:'Natal planets', resetAll:'Reset all',
    progLunarPhases:'Prog. lunar phases',
    privacyMode:'Hide name & date',
    skyNowTitle:'Sky now', skySetPlace:'set location',
    vocFromTo:'☽︎ void of course {from}–{to}', vocUntil:'☽︎ void of course until {to}',
    homeEvents:'Events', homeAll:'All', homePinned:'Pinned',
    homeSearchPlaceholder:'Search by name or city…', newChart:'+ New chart',
    homeNothingFound:'Nothing found',
    pinTitle:'Pin', unpinTitle:'Unpin', groupTitle:'Group',
    exactOn:'exact', turnsYears:'turns {n}',
    panelTabData:'Data', panelTabNotes:'Notes', panelTabGrades:'Degrees', panelTabAspects:'Aspects',
    noteNew:'+ New note', noteUntitled:'Untitled',
    notesEmpty:'No notes yet',
    notesLoginFirst:'Sign in to add notes',
    notesSaveChartFirst:'Save the chart to add notes',
    notesError:'Failed to load notes',
    noteTitlePlaceholder:'Title…',
    noteDeleteConfirm:'Delete note "{name}"?',
    noteBackTitle:'Back to list', notePreviewTitle:'Preview', noteExportTitle:'Export .md',
    phaseName_0:'New Moon', phaseName_45:'Crescent',
    phaseName_90:'First Quarter', phaseName_135:'Gibbous',
    phaseName_180:'Full Moon', phaseName_225:'Disseminating',
    phaseName_270:'Last Quarter', phaseName_315:'Balsamic',
    byMonths:'by months', byYears:'by years', prLabel:'Pr', dirLabel:'Dir',
    prPrefix:'pr ', dirPrefix:'dir ', trPrefix:'tr', natPrefix:'nat',
    houseWord:'House', cuspWord:'Cusp',
    angularNames:{ 0:'Ascendant', 3:'IC', 6:'Descendant', 9:'MC' },
    rulerLabel:'Ruler:', housePrefix:'House ',
    pl_sun:'Sun', pl_moon:'Moon', pl_mercury:'Mercury', pl_venus:'Venus',
    pl_mars:'Mars', pl_jupiter:'Jupiter', pl_saturn:'Saturn', pl_uranus:'Uranus',
    pl_neptune:'Neptune', pl_pluto:'Pluto', pl_nnode:'N. Node',
    pl_lilith:'Lilith', pl_chiron:'Chiron', pl_snode:'S. Node', pl_nodes:'Nodes',
    signs:['Aries','Taurus','Gemini','Cancer','Leo','Virgo','Libra','Scorpio','Sagittarius','Capricorn','Aquarius','Pisces'],
    asp_conjunction:'Conjunction', asp_sextile:'Sextile',
    asp_square:'Square', asp_trine:'Trine', asp_opposition:'Opposition',
    months:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],
  },
};
